version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: storeflex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: storeflex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - storeflex-network

  redis:
    image: redis:7-alpine
    container_name: storeflex-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - storeflex-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: storeflex-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/storeflex
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - storeflex-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: storeflex-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - storeflex-network

volumes:
  postgres_data:
  redis_data:

networks:
  storeflex-network:
    driver: bridge